export const GET_SAMPLES_REQUEST = 'GET_SAMPLES_REQUEST'
export const GET_SAMPLES_SUCCESS = 'GET_SAMPLES_SUCCESS'
export const GET_SAMPLES_FAIL = 'GET_SAMPLES_FAIL'

export const UPLOAD_REQUEST = 'UPLOAD_REQUEST'
export const UPLOAD_LOADING_PERCENTAGE = 'UPLOAD_LOADING_PERCENTAGE'
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS'
export const UPLOAD_FAIL = 'UPLOAD_FAIL'

export const GET_UPLOADS_REQUEST = 'GET_UPLOADS_REQUEST'
export const GET_UPLOADS_SUCCESS = 'GET_UPLOADS_SUCCESS'
export const GET_UPLOADS_FAIL = 'GET_UPLOADS_FAIL'

export const DELETE_IMAGE_REQUEST = 'DELETE_IMAGE_REQUEST' 
export const DELETE_IMAGE_FAIL = 'DELETE_IMAGE_FAIL' 
export const DELETE_IMAGE_SUCCESS = 'DELETE_IMAGE_SUCCESS' 

